WebApplication1/Models/Animal.cs
namespace WebApplication1.Models
{
    public class Animal
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Link { get; set; }
        public string Image { get; set; }
    }
}

WebApplication1/Models/Components/Card.cs
namespace WebApplication1.Models.Components
{
    public class Card
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImgSrc { get; set; }
        public string ImgAlt { get; set; }
        public string FooterText { get; set; }
    }
}

WebApplication1/Pages/CreateAnimal.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Animals
{
    public class CreateAnimalModel : PageModel
    {
        private readonly AnimalContext _context;

        public List<Animal> Animals { get; set; }

        public CreateAnimalModel(AnimalContext context)
        {
            _context = context;

            Animals = context.Animal.ToList();
        }

        public void OnPostCreate(string type, string image, string link)
        {
            var animal = new Animal
            {
                Image = image,
                Link = link,
                Type = type,
            };

            _context.Add(animal);
            _context.SaveChanges();
        }

        public IActionResult OnPostGetAnimalData(int id)
        {
            var animal = _context.Animal.Find(id);

            return new JsonResult(animal);
        }

        public void OnPostUpdate(string type, string image, string link, int id)
        {
            var animal = _context.Animal.Find(id);
            if (animal == null) return;

            animal.Image = image;
            animal.Link = link;
            animal.Type = type;

            _context.SaveChanges();
        }

        public void OnPostDelete(int id)
        {
            var animal = _context.Animal.Find(id);
            if (animal == null) return;

            _context.Animal.Remove(animal);
            _context.SaveChanges();
        }
    }
}

WebApplication1/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication1/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApplication1/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace WebApplication1.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            string dateTime = DateTime.Now.ToString("d", new CultureInfo("en-US"));
            ViewData["TimeStamp"] = dateTime;
        }
    }
}

WebApplication1/Pages/Shared/Components/Card.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages.Shared.Components
{
    public class CardModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication1/Pages/Animals.cshtml
@page
@using WebApplication1.Models;
@model WebApplication1.Pages.AnimalsModel
@{
    ViewData["Title"] = "Animals";
}

<!--Here is the layout for the animals page-->

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alkatra&family=Dosis:wght@200&family=Indie+Flower&family=Montserrat:wght@100&family=Noto+Serif&family=Shadows+Into+Light&family=Shantell+Sans:ital,wght@1,300&display=swap" rel="stylesheet">
</head>

<h1>Djursidan</h1>

@if(Model.Animals.Count > 0)
{
    @foreach (var animal in Model.Animals)
    {
        <div class="container-fluid">
            <div class="column">
                <div class="flip-card">
                    <div class="flip-card-inner">
                        <div class="flip-card-front">
                            <img src="@animal.Image" class="rounded"  />
                            <figure>
                                <figcaption>
                                    <p>@animal.Type</p>
                                </figcaption>
                            </figure>
                            
                        </div>
                        <div class="flip-card-back">
                            <p>@animal.Type</p>
                            <a asp-page="@animal.Link">Se mer</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
    }

}
else
{
    <p>Finns inga djur!</p>
}

WebApplication1/Pages/Animals/Bunny.cshtml
@page
@model WebApplication1.Pages.Animals.BunnyModel
@{
}
<p>BUNBUN</p>

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var card in Model.Cards)
    {
        @await Html.PartialAsync("~/Pages/Shared/Components/Card.cshtml", card)
    }
</div>

WebApplication1/Pages/Animals/Dog.cshtml
@page
@model WebApplication1.Pages.Animals.DogModel
@{
    ViewData["Title"] = "Hund";
}

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alkatra&family=Dosis:wght@200&family=Indie+Flower&family=Montserrat:wght@100&family=Noto+Serif&family=Shadows+Into+Light&family=Shantell+Sans:ital,wght@1,300&display=swap" rel="stylesheet">
</head>



<h1 class="display-4">Animal Kingdom | Canis lupus familiaris </h1>

<div>
    <figure>
        <img class="img-test" src="/images/pug2.png" />
        <figcaption>Mops</figcaption>
    </figure>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach(var card in Model.Cards)
    {
        @await Html.PartialAsync("~/Pages/Shared/Components/Card.cshtml", card)
    }
</div>


<div class="container_test_img">
    <div class="image">
        <img src="~/images/wolf.jpeg" />
    </div>
    <div class="text">
        <h4>Människans äldsta följeslagare</h4>
        <p>
            Hunden var det allra första djuret som domesticerades utav människan för ca 20 000 - 40 000 år sedan,
            det gick till genom att vargflockarna höll sig nära människan och åt från matrester.
            Efter varje generation varg som föddes så blev de tamare men också att utseendet började förändras till att likna mer hund.
            <br />
            I den yngre stenåldern där man började med jordbruk och boskapsskötsel, började människan också med selektiv avel,
           med selektiv avel så började hundraserna ta form.
        </p>
    </div>
</div>


            

WebApplication1/Pages/CreateAnimal.cshtml
@page
@model WebApplication1.Pages.Animals.CreateAnimalModel

<h2>Hantera djur</h2>

<script>

    window.addEventListener('load', (event) => {
        if (document.getElementById("select_animal_update") !== null){
            document.getElementById("select_animal_update").addEventListener('change', (event) => {
                getAnimal(event.currentTarget.value);
            });
        }
    });

    function getAnimal(id){
        $.ajax({
            type: "POST",
            url: '?handler=GetAnimalData',
            headers: {
                RequestVerificationToken: $('input:hidden[name="__RequestVerificationToken"]').val(),
            },
            data: { "id": id,
            dataType: "json"}
        }).done(function(data){

            document.getElementById("animal_update_id").value = data.id;
            document.getElementById("animal_update_type").value = data.type;
            document.getElementById("animal_update_link").value = data.link;
            document.getElementById("animal_update_image").value = data.image;

            $("#form_animal_update").show();
        });
    }
</script>

<div class="accordion" id="container_accordion">
    <div class="accordion-item">
        <h2 class="accordion-header" id="heading_createanimal">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#container_createanimal" aria-expanded="false" aria-controls="container_createanimal">
                Skapa djur
            </button>
        </h2>
        <div id="container_createanimal" class="accordion-collapse collapse" aria-labelledby="heading_createanimal" data-bs-parent="#container_accordion">
            <div class="accordion-body">
                <form asp-page-handler="create" method="post">
                    <div class="mb-3">
                        <label for="animal_type" class="form-label">Typ</label>
                        <input class="form-control" id="animal_type" type="text" name="type" aria-describedby="animal_type_description" required />
                        <div id="animal_type_description" class="form-text">
                            Vad för typ av djur?(Häst,räv osv..)
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="animal_link" class="form-label">Länk</label>
                        <input class="form-control" id="animal_link" type="text" name="link" aria-describedby="animal_link_description" required />
                        <div id="animal_link_description" class="form-text">
                            Sökväg till sida för djuret.
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="animal_image" class="form-label">Bild</label>
                        <input class="form-control" id="animal_image" type="text" name="image" aria-describedby="animal_image_description" required />
                        <div id="animal_image_description" class="form-text">
                            Sökväg till bild för djuret.
                        </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Skapa</button>
                </form>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="heading_updateanimal">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#container_updateanimal" aria-expanded="false" aria-controls="container_updateanimal">
                Uppdatera djur
            </button>
        </h2>
        <div id="container_updateanimal" class="accordion-collapse collapse" aria-labelledby="heading_updateanimal" data-bs-parent="#container_accordion">
            <div class="accordion-body">
                <div class="accordion-body">
                    @if (Model.Animals.Count > 0)
                    {
                        <select class="form-select form-select-lg mb-3" id="select_animal_update">
                            <option selected>Välj djur</option>
                            @foreach (var animal in Model.Animals)
                            {
                                <option value="@animal.Id">@animal.Type</option>
                            }
                        </select>
                        <form asp-page-handler="update" method="post" style="display:none;" id="form_animal_update">
                            <div class="mb-3">
                                <label for="animal_update_id" class="form-label">Id</label>
                                <input class="form-control" id="animal_update_id" type="text" name="id" readonly/>
                            </div>
                            <div class="mb-3">
                                <label for="animal_update_type" class="form-label">Typ</label>
                                <input class="form-control" id="animal_update_type" type="text" name="type" aria-describedby="animal_update_type_description" required />
                                <div id="animal_update_type_description" class="form-text">
                                    Vad för typ av djur?(Häst,Räv osv..)
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="animal_update_link" class="form-label">Länk</label>
                                <input class="form-control" id="animal_update_link" type="text" name="link" aria-describedby="animal_update_link_description" required />
                                <div id="animal_update_link_description" class="form-text">
                                    Sökväg till sida för djuret.
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="animal_update_image" class="form-label">Bild</label>
                                <input class="form-control" id="animal_update_image" type="text" name="image" aria-describedby="animal_update_image_description" required />
                                <div id="animal_update_image_description" class="form-text">
                                    Sökväg till bild för djuret.
                                </div>
                            </div>
                            <input type="submit" class="btn btn-primary" value="Uppdatera" />
                        </form>
                    }
                    else
                    {
                        <p>Finns inga djur!</p>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="heading_deleteanimal">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#container_deleteanimal" aria-expanded="false" aria-controls="container_deleteanimal">
                Ta bort djur
            </button>
        </h2>
        <div id="container_deleteanimal" class="accordion-collapse collapse" aria-labelledby="heading_deleteanimal" data-bs-parent="#container_accordion">
            <div class="accordion-body">
                @if (Model.Animals.Count > 0)
                {
                    <form asp-page-handler="delete" method="post">
                        <select class="form-select form-select-lg mb-3" name="id">
                            <option selected>Välj djur</option>
                            @foreach (var animal in Model.Animals)
                            {
                                <option value="@animal.Id">@animal.Type</option>
                            }
                        </select>
                        <input type="submit" class="btn btn-primary" value="Ta bort" />
                    </form>
                }
                else
                {
                    <p>Finns inga djur!</p>
                }
            </div>
        </div>
    </div>
</div>

WebApplication1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<!--Here is the layout for Home page content-->

<div class="text-center">
    <h1 class="display-4">Animal Kingdom</h1>
</div>

<div>
    <p>Bobo - Verktyg</p>
    <ul>
        <li>
            <a class="nav-link text-dark" asp-area="" asp-page="/CreateAnimal"> Hantera djur</a>
        </li>
    </ul>
</div>

WebApplication1/Pages/Shared/Components/Card.cshtml
@model WebApplication1.Models.Components.Card

<style>
    .card-title {
        color: red;
        text-align:center;
    }
    .card-img-top {
        width: 180px;
        align-items:center;
        margin-left:auto;
        margin-right:auto;
        padding: 1.5rem;
    }
   /* .col {
        font-family:'Bodoni MT';
        padding:20px;
        color:brown;
    }*/
    .card-wrapper {
        color:blue;
        font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        padding: 10px 10px 10px 10px;
    }
    


    
</style>


<div class="">
    <div class="card h-100">
        <img src="@Model.ImgSrc" class="card-img-top" alt="@Model.ImgAlt">
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
        </div>
        <div class="card-footer">
            <small class="text-body-secondary">@Model.FooterText</small>
        </div>
    </div>
</div>

WebApplication1/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
 <!--Here is the layout for the entire website. Header, navbar, footer etc.-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Animal Kingdom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="font-awesome-animation.min.css">
    <script src="https://kit.fontawesome.com/3888d8353b.js" crossorigin="anonymous"></script>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                 <a class="navbar-brand" asp-area="" asp-page="/Index">| C# projektet | </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-evenly">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index"><i class="fa-solid fa-house"></i> Hem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Animals"><i class="fa-solid fa-kiwi-bird"></i> Djur</a>   
                        </li>
                    </ul>
                </div>
                <div class="container-searchbar">
                    <form action="/" method="GET" class="form">
                        <input type="text" placeholder="Sök..."  class="search-field"/>
                        <button type="submit" class="search-button">
                            <img src="~/images/search.jpg" />
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="bg-dark text-center text-lg-start text-white">
        <div class="container p-4">
            <div class="row mt-4">
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">C# projektet</h5>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <p class="text-white">
                                I C# projektet håller jag på att bygga upp en hemsida med olika djurarter. Syftet med detta är för att jag ska få en ökad
                                förståelse i C# programmering, backend och frontend utveckling.
                            </p>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">C# projektet</h5>
                    <ul class="list-unstyled mb-0 ">
                        <li>
                            <a asp-page="/Animals" class="text-white">
                                <i class="fa-solid fa-kiwi-bird fa-xl fa-fw me-2"></i> Djur
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Kontakt info</h5>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <a class="text-white">
                                <i class="fa-solid fa-house fa-xl fa-fw me-2"></i> Åshammar, Gästriklands län
                            </a>
                        </li>
                        <li> 
                            <a href="mailto:linda.forslund92@outlook.com" class="text-white" onmouseover="onEnter(this)" onmouseout="onLeaving(this)">
                                <i id="pappaforslund" class="fa fa-regular fa-envelope fa-xl fa-fw me-2"></i> linda.forslund92@outlook.com
                            </a>
                        </li>
                        <li> 
                            <a class="text-white">
                                <i class="fa-solid fa-phone fa-xl fa-fw me-2"></i> 070 | 227 06 09
                              </a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Sociala medier</h5>
                    <ul class="list-unstyled mb-0" id="HELLO">
                        <li>
                            <a class="text-white" href="#">
                                <i class="fa-brands fa-github fa-xl fa-fw me-2"></i> Github
                            </a>
                        </li>
                        <li>
                            <a class="text-white" href="https://www.facebook.com/linda.l.godin/">
                                <i class="fa-brands fa-facebook fa-xl fa-fw me-2"></i> Facebook
                            </a>
                        </li>
                        <li>
                            <a class="text-white" href="https://www.linkedin.com/in/linda-forslund-240258161/">
                                <i class="fa-brands fa-linkedin fa-xl fa-fw me-2 "></i> LinkedIn
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div> 
    </footer>

@*    <footer class="border-top footer text-white text-center">
        <div>
            <h4>Animal Kingdom</h4>
            
            &copy; 2023 - HELLO - <a asp-area="" asp-page="/Privacy">Privacy</a> 
            <h6>Kontakta mig:</h6>
            <p>Maila mig!</p> <a href="mailto:linda.forslund92@outlook.com"><i class="fa-regular fa-envelope fa-beat fa-xl"></i></a>
            
        </div>
    </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
      

        //function onEnter(linkElement){
        //    var iElement = linkElement.querySelector("#pappaforslund");
        //    iElement.classList.add("fa-beat");
        //}

        //function onLeaving(linkElement) {
        //    var iElement = linkElement.querySelector("#pappaforslund");
        //    iElement.classList.remove("fa-beat");
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>